# -*- coding: utf-8 -*-
"""house_price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/116A90ys2PBVcWuj7Qjt38ylYSNs6q_om
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Load the dataset
df = pd.read_csv('house_price.csv')

# Split the dataset into features (X) and target (y)
X = df[['bedrooms', 'sqft']]
y = df['price']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a linear regression model
model = LinearRegression()

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = model.predict(X_test)

# Evaluate the model using mean squared error and R-squared
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error: {mse:.2f}')
print(f'R-squared: {r2:.2f}')

# Use the model to make predictions on new data
new_data = pd.DataFrame({'bedrooms': [4], 'sqft': [2300]})
new_pred = model.predict(new_data)
print(f'Predicted price for 4 bedrooms and 2300 sqft: {new_pred[0]:.2f}')

